/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as swapRouterUpgradeableSol from "./SwapRouterUpgradeable.sol";
export type { swapRouterUpgradeableSol };
export type { TBot } from "./TBot";
export type { TTether } from "./TTether";
